export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_IN_PROGRESS = "LOGIN_IN_PROGRESS";

export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const FETCH_IN_PROGRESS = "FETCH_IN_PROGRESS";
